openapi: '3.0.2'
info:
  title: Opportunity Management API
  version: '1.0'
  description: API for managing business opportunities

servers:
  - url: https://ag-customer-api.azurewebsites.net/opportunities/  # Replace with actual server URL

components:
  schemas:
    Opportunity:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the opportunity
        opportunityID:
          type: string
          description: External opportunity identifier
        name:
          type: string
          description: Name of the opportunity
        description:
          type: string
          description: Detailed description of the opportunity
        account:
          type: string
          description: Name of the account associated with the opportunity
        parentAccount:
          type: string
          description: Name of the parent account
        parentAccountId:
          type: integer
          description: Unique identifier of the parent account
        territory:
          type: string
          description: Sales territory for the opportunity
        probability:
          type: number
          format: float
          description: Probability of closing the opportunity
        stageName:
          type: string
          description: Current stage of the sales opportunity
        amount:
          type: number
          format: double
          description: Monetary value of the opportunity
        currency:
          type: string
          description: Currency of the opportunity amount
        owner:
          type: string
          description: Name of the opportunity owner
        region:
          type: string
          description: Geographic region of the opportunity
        serviceLine:
          type: string
          description: Service line associated with the opportunity
        dateCreated:
          type: string
          format: date-time
          description: Date and time when the opportunity was created
        closeDate:
          type: string
          format: date-time
          description: Expected or actual date of opportunity closure
      required:
        - id
        - name
        - account

paths:
  /:
    get:
      summary: Get all opportunities
      operationId: GetAllOpportunities
      tags:
        - Opportunity
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Opportunity'

    post:
      summary: Create a new opportunity
      operationId: CreateOpportunity
      tags:
        - Opportunity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Opportunity'
      responses:
        '201':
          description: Opportunity created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Opportunity'

  /{id}:
    get:
      summary: Get a specific opportunity by ID
      operationId: GetOpportunityById
      tags:
        - Opportunity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Opportunity'
        '404':
          description: Opportunity not found

    put:
      summary: Update an existing opportunity
      operationId: UpdateOpportunity
      tags:
        - Opportunity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Opportunity'
      responses:
        '204':
          description: Opportunity updated successfully
        '404':
          description: Opportunity not found

    delete:
      summary: Delete an opportunity
      operationId: DeleteOpportunity
      tags:
        - Opportunity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Opportunity deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Opportunity'
        '404':
          description: Opportunity not found

  /account/{accountName}:
    get:
      summary: Get opportunities by account name
      operationId: GetOpportunitiesByAccountName
      tags:
        - Opportunity
      parameters:
        - name: accountName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Opportunity'

  /parentAccount/{parentAccountName}:
    get:
      summary: Get opportunities by parent account name
      operationId: GetOpportunitiesByParentAccountName
      tags:
        - Opportunity
      parameters:
        - name: parentAccountName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Opportunity'