openapi: '3.0.2'
info:
  title: Order Header Management API
  version: '1.0'
  description: API for managing order headers

servers:
  - url: https://ag-customer-api.azurewebsites.net/orderheaders/  # Replace with actual server URL

components:
  schemas:
    OrderHeader:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the order header
        salesDocNumber:
          type: string
          description: Sales document number
        localCustomer:
          type: string
          description: Name of the local customer
        parentCustomer:
          type: string
          description: Name of the parent customer
        opportunityID:
          type: integer
          description: Associated opportunity identifier
        salesDocType:
          type: string
          description: Type of sales document
        salesOrganisation:
          type: string
          description: Sales organization
        distributionChannel:
          type: string
          description: Distribution channel
        parentCustomerID:
          type: string
          description: Identifier for the parent customer
        localCustomerID:
          type: string
          description: Identifier for the local customer
        dateCreated:
          type: string
          format: date-time
          description: Date and time when the order header was created
        createdBy:
          type: string
          description: User who created the order header
      required:
        - id
        - salesDocNumber
        - localCustomer
        - parentCustomer

paths:
  /:
    get:
      summary: Get all order headers
      operationId: GetAllOrders
      tags:
        - OrderHeader
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderHeader'

    post:
      summary: Create a new order header
      operationId: CreateOrder
      tags:
        - OrderHeader
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderHeader'
      responses:
        '201':
          description: Order header created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderHeader'

  /{id}:
    get:
      summary: Get a specific order header by ID
      operationId: GetOrderById
      tags:
        - OrderHeader
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderHeader'
        '404':
          description: Order header not found

    put:
      summary: Update an existing order header
      operationId: UpdateOrder
      tags:
        - OrderHeader
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderHeader'
      responses:
        '204':
          description: Order header updated successfully
        '404':
          description: Order header not found

    delete:
      summary: Delete an order header
      operationId: DeleteOrder
      tags:
        - OrderHeader
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order header deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderHeader'
        '404':
          description: Order header not found

  /parentCustomer/{parentCustomer}:
    get:
      summary: Get order headers by parent customer name
      operationId: GetAllOrdersByCustomerName
      tags:
        - OrderHeader
      parameters:
        - name: parentCustomer
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderHeader'

  /localCustomer/{localCustomer}:
    get:
      summary: Get order headers by local customer name
      operationId: GetAllOrdersByLocalCustomerName
      tags:
        - OrderHeader
      parameters:
        - name: localCustomer
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderHeader'

  /opportunity/{opportunityId}:
    get:
      summary: Get order headers by opportunity ID
      operationId: GetAllOrdersByOpportunityId
      tags:
        - OrderHeader
      parameters:
        - name: opportunityId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderHeader'